### PR TITLE
fix: no hardcoded models

### LINKED ISSUE #205: Use actual model in pipelines
models in the stable diffusion pielines are currently hardcoded. Once the file structure is fixed we need to make sure we use them in the piplines

### PR DESCRIPTION
**Pull request by pixelass**
## Motivation
allow client to load models on startup

## Issues closed
closes #205

### CODE REVIEW

File: src/electron/future/ipc/sdk.ts [hunk 1]
```diff
@@ -61,12 +62,28 @@ ipcMain.on(
...
 		}
 
+		const {
+			model = "stabilityai/sd-turbo/fp16",
+			vae = "madebyollin/taesd",
+			stablefast,
+		} = message.payload;
+
+		console.log("Live Painting is running for app with ID:", message.payload?.appId);
+		console.log("Live Painting is using:", { model, vae });
```
Comment (TimPietrusky) [inline src/electron/future/ipc/sdk.ts]: Please use `logger.info` if this is something that should stay or remove it otherwise.

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
LGTM, I have just one remark regarding the usage of console.log!
